### ISSUE TITLE
octan or swool

### ISSUE THREAD

**Issue by mohsenmojadam2019** [systemsdk/docker-apache-php-laravel#31]
hi 
please add octan or swool for speed 
Thankful

**Comment by dimadeush** [comment]
Hello
docker-apache-php-laravel is basically an environment with standard tools for your development. Swool or octane are not standard tools and they have some benefits and drawbacks. Also not all developers are using specific tools and we don't want that other developers need to delete specific tools before using docker-apache-php-laravel. You can find more info about benefits and drawbacks using next link - https://chriswhite.is/coding/swoole-vs-roadrunner-for-laravel-octane/. So if you want to use some specific tools you are able to extend your environment and add necessary tools and packages.
Thanks
